export const Users = [
{
    id:1,
    profilePicture:"person/1.jpg",
    username:"Rohin gai",
},
{
    id:2,
    profilePicture:"person/2.jpg",
    username:"roge mark",
},
{
    id:4,
    profilePicture:"person/4.jpg",
    username:"tanya stark",
},
{
    id:5,
    profilePicture:"person/5.jpg",
    username:"alexa albert",
},
{
    id:6,
    profilePicture:"person/6.jpg",
    username:"monat par",
},
{
    id:7,
    profilePicture:"person/7.jpg",
    username:"susmet sehh",
},
{
    id:8,
    profilePicture:"person/8.jpg",
    username:"kam nam",
},
{
    id:9,
    profilePicture:"person/9.jpg",
    username:"kipin domer",
},
{
    id:10,
    profilePicture:"person/10.jpg",
    username:"sarasai e",
},

];

export const Posts =[
    {
        id:1,
        desc:"love for all",
        photo:"post/1..jpg",
        date:"5 mins ago",
        userId:1,
        like:37,
        Comment:7,
    },
    {
        id:2,
        desc:"peace",
        photo:"post/2..jpg",
        date:"13 mins ago",
        userId:2,
        like:97,
        Comment:32,
    },
    {
        id:3,
        desc:"nature lover",
        photo:"post/3..jpg",
        date:"12 mins ago",
        userId:3,
        like:375,
        Comment:79,
    },
    {
        id:4,
        desc:"liked it",
        photo:"post/4..jpg",
        date:"23 mins ago",
        userId:4,
        like:3,
        Comment:4,
    },
    {
        id:5,
        desc:"social",
        photo:"post/5..jpg",
        date:"32 mins ago",
        userId:5,
        like:237,
        Comment:3,
    },
    {
        id:6,
        desc:"feel bleesed",
        photo:"post/6..jpg",
        date:"1 hour ago",
        userId:6,
        like:217,
        Comment:54,
    },
    {
        id:7,
        photo:"post/7..jpg",
        date:"1.3 hour ago",
        userId:7,
        like:12,
        Comment:1,
    },
    {
        id:8,
        photo:"post/8..jpg",
        date:"2 hour ago",
        userId:8,
        like:3,
        Comment:1,
    },
    {
        id:9,
        desc:"like hate's",
        photo:"post/9..jpg",
        date:"1 week ago",
        userId:9,
        like:447,
        Comment:201,
    },
]